-- WARNING: This script deletes all users and admins and recreates a secure admin.
-- Run in a safe environment/backup first.

SET SQL_SAFE_UPDATES = 0;

-- Purge user-related tables
DELETE FROM user_address;
DELETE FROM user_avatar;
DELETE FROM `user`;

-- Purge admins
DELETE FROM admin;

-- Create a secure admin placeholder; set password hash externally in PHP or replace below
-- Note: Replace the hash with one generated by PHP password_hash. Example shown for "Admin@12345".
-- The hash below is a placeholder and should be replaced during deployment.
-- Replace the two placeholders below with values you generate with PHP:
--   1) SALT_HEX: 32-hex chars (bin2hex(random_bytes(16)))
--   2) HASH_HEX: hash('sha256', SALT_HEX . 'YourPassword')
INSERT INTO admin(fullname, username, password, salt, number_phone, start_date, position, feature)
VALUES ('Super Admin', 'admin', 'HASH_HEX', 'SALT_HEX', '0000000000', CURDATE(), 'superadmin', 'all');

SET SQL_SAFE_UPDATES = 1;


